language: c


matrix:
 include:
    - os: linux
      dist: trusty
      compiler: gcc

before_install:
  - sudo apt-get install --assume-yes --quiet gcc-multilib &&
    sudo apt-get install --assume-yes cpputest
script:
  - echo "Hello"
