language: c


matrix:
 include:
    - os: linux
      dist: trusty
      compiler: gcc

before_install:
  - sudo apt-get install --assume-yes --quiet gcc-multilib
  - git clone https://github.com/ThrowTheSwitch/Unity.git
install:
  - gem install rspec
  - gem install rubocop
script:
  - ls
  - gcc -I./Unity/src/ -I./src/ ./test/dt.c src/d.c ./Unity/src/unity.c -o tde
  - ./tde 